export const products = [
    {
      image: "./src/assets/model.png",
      name: " Lorem ipsum dolor sit amet consectetuer adipiscing elit",
      price: "R$ 100,00",
      discount: "R$ 79,90",
      offer: "10% OFF",
      installments: "Ou em até 10x de R$ 7,90",
    },
    {
      image: "./src/assets/model.png",
      name: " Lorem ipsum dolor sit amet consectetuer adipiscing elit",
      price: "R$ 100,00",
      discount: "R$ 79,90",
      offer: "10% OFF",
      installments: "Ou em até 10x de R$ 7,90",
    },
    {
      image: "./src/assets/model.png",
      name: " Lorem ipsum dolor sit amet consectetuer adipiscing elit",
      price: "R$ 100,00",
      discount: "R$ 79,90",
      offer: "10% OFF",
      installments: "Ou em até 10x de R$ 7,90",
    },
    {
      image: "./src/assets/model.png",
      name: " Lorem ipsum dolor sit amet consectetuer adipiscing elit",
      price: "R$ 100,00",
      discount: "R$ 79,90",
      offer: "10% OFF",
      installments: "Ou em até 10x de R$ 7,90",
    },
    {
      image: "./src/assets/model.png",
      name: " Lorem ipsum dolor sit amet consectetuer adipiscing elit",
      price: "R$ 100,00",
      discount: "R$ 79,90",
      offer: "10% OFF",
      installments: "Ou em até 10x de R$ 7,90",
    },
    {
      image: "./src/assets/model.png",
      name: " Lorem ipsum dolor sit amet consectetuer adipiscing elit",
      price: "R$ 100,00",
      discount: "R$ 79,90",
      offer: "10% OFF",
      installments: "Ou em até 10x de R$ 7,90",
    },
    {
      image: "./src/assets/model.png",
      name: " Lorem ipsum dolor sit amet consectetuer adipiscing elit",
      price: "R$ 100,00",
      discount: "R$ 79,90",
      offer: "10% OFF",
      installments: "Ou em até 10x de R$ 7,90",
    },
    {
      image: "./src/assets/model.png",
      name: " Lorem ipsum dolor sit amet consectetuer adipiscing elit",
      price: "R$ 100,00",
      discount: "R$ 79,90",
      offer: "10% OFF",
      installments: "Ou em até 10x de R$ 7,90",
    },
  ];